name: Wellspace
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ">=3.6.0"


dependencies:
  flutter:
    sdk: flutter


 
  flutter_localizations:
    sdk: flutter


  http: ^0.13.4
  flutter_secure_storage: ^9.0.0
  lottie: ^2.2.0
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.0.7
  jwt_decode: ^0.3.1
  provider: ^6.1.5
  dotted_border: ^2.1.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/animations/splash_animation.json